on: [push, pull_request]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    name: Build Documents
    steps:
      - name: ðŸš§ Set up Git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: âš™ Build LaTeX files
        run: |
          docker run -i --rm -v "$(pwd)/:/work" -w /work ghcr.io/xu-cheng/texlive-full bash -c '
            shopt -s globstar
            set -e
            for d_path in ./**/d_*.tex; do (
              cd "$(dirname $d_path)"
              latexmk -lualatex $(basename $d_path)
            ) done'
            
      - name: ðŸ§¬ Generate artifact containing PDF files
        uses: actions/upload-artifact@v3
        with:
          name: documentazione
          path: "**/*.pdf"

  build_ghpages:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    name: Build GitHub Pages
    needs: build_docs
    steps:
      - name: ðŸš§ Set up Git repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      
      - name: â¬‡ Download artifact documentazione
        uses: actions/download-artifact@v3.0.1
        with:
          name: documentazione
          path: ./documentazione

      # Grazie ad @augustozanellato per la scoperta di apindex
      - name: âš’ Install apindex and update HTML template
        run: |
          git clone --depth=1 https://github.com/paperbenni/apindex.git
          cd apindex
          rm share/apindex/index.template.html
          curl -o share/apindex/index.template.html https://raw.githubusercontent.com/SWEasabi/global-assets/main/html/ghpages_template.html
          sed -i "34d; 35i Documentazione" share/apindex/index.template.html
          cmake . -DCMAKE_INSTALL_PREFIX=/usr
          sudo make install
          cd ..
          rm -rf apindex
        
      - name: âš™ Build static page
        run: apindex ./documentazione
        
      - name: ðŸ§¬ Generate artifact containing Directory Listings Page
        uses: actions/upload-artifact@v3
        with:
          name: documentazione_html
          path: ./documentazione
